services:
  mysql:
    image: mysql:8.0
    container_name: MYSQL_DATABASE
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - db
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - db
volumes:
  mysql-data:
networks:
  db:
