# Sử dụng base image node:18-alpine
FROM node:18-alpine AS build

# Thiết lập thư mục làm việc
WORKDIR /usr/src/app

# Sao chép file package.json và cài đặt dependency
COPY package.json ./
RUN npm install

# Sao chép mã nguồn và build ứng dụng
COPY . .
RUN npm run build

# Sử dụng image thứ hai để phục vụ ứng dụng
FROM node:18-alpine
RUN npm install -g serve
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/build ./build

# Mở cổng 3000
EXPOSE 3000

# Chạy ứng dụng
CMD ["serve", "-s", "build", "-l", "3000"]