version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: rootpassword
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql